# Generated by Django 3.0 on 2020-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='end_timemodel',
            new_name='end_time',
        ),
    ]
